// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Data;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(DbContextFirst))]
    [Migration("20251029161219_cv")]
    partial class cv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test.Models.AccessRoadType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessRoad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccessRoadType");
                });

            modelBuilder.Entity("Test.Models.AdditionalCostModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AdditionalCostTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CostType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ducom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsSelected")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AdditionalCostTypeId");

                    b.HasIndex("UserID");

                    b.ToTable("AdditionalCostModels");
                });

            modelBuilder.Entity("Test.Models.AdditionalCostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalCostTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("AdditionalCostType");
                });

            modelBuilder.Entity("Test.Models.Almjal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AlmjalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Almjals");
                });

            modelBuilder.Entity("Test.Models.AreaStandardFromTo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AreaStandardTemplateId")
                        .HasColumnType("int");

                    b.Property<decimal>("AreaTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostOfSurveyingDevice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ParentTemplateId")
                        .HasColumnType("int");

                    b.Property<decimal>("SurveyingDeviceCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AreaStandardTemplateId");

                    b.ToTable("AreaStandardFromTo");
                });

            modelBuilder.Entity("Test.Models.AreaStandardTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("AreaStandardTemplate");
                });

            modelBuilder.Entity("Test.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almgal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Test.Models.Characteristicperson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characteristicpeople");
                });

            modelBuilder.Entity("Test.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlmjalId")
                        .HasColumnType("int");

                    b.Property<string>("ClassificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlmjalId");

                    b.ToTable("Classification");
                });

            modelBuilder.Entity("Test.Models.ContractAmendment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmendmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EngineerId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkContractId");

                    b.ToTable("contractAmendments");
                });

            modelBuilder.Entity("Test.Models.ContractItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkContractId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkContractId");

                    b.ToTable("contractItems");
                });

            modelBuilder.Entity("Test.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("Test.Models.EarthBorders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BorderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difference1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Difference12")
                        .HasColumnType("int");

                    b.Property<int?>("IdenticalOrDifferent")
                        .HasColumnType("int");

                    b.Property<int?>("TanjezOrderID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TanjezOrderID");

                    b.HasIndex("UserID");

                    b.ToTable("EarthBorders");
                });

            modelBuilder.Entity("Test.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTasks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StillWorking")
                        .HasColumnType("bit");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Test.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExperienceId")
                        .HasColumnType("int");

                    b.Property<string>("JobGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Test.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReciveId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Test.Models.OfferTypeModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("IsSelected")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("OfferTypeModels");
                });

            modelBuilder.Entity("Test.Models.PlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlaceType");
                });

            modelBuilder.Entity("Test.Models.PriceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaStandardTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("ParentOfferId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReportFromInDay")
                        .HasColumnType("int");

                    b.Property<int>("ReportToInDay")
                        .HasColumnType("int");

                    b.Property<int>("SectionTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PriceTable");
                });

            modelBuilder.Entity("Test.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProjCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Test.Models.PurposeSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("purposeSurveys");
                });

            modelBuilder.Entity("Test.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EduCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduDept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduMajor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduUniv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("Test.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sections");
                });

            modelBuilder.Entity("Test.Models.SectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("SectionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("sectionTypes");
                });

            modelBuilder.Entity("Test.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SkillDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Test.Models.SpecificSpaceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlmjalID")
                        .HasColumnType("int");

                    b.Property<int?>("BiggerThan")
                        .HasColumnType("int");

                    b.Property<int?>("FromDate")
                        .HasColumnType("int");

                    b.Property<int?>("LessThan")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("PriceWithDevice")
                        .HasColumnType("int");

                    b.Property<int?>("Space")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceFrom")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceTo")
                        .HasColumnType("int");

                    b.Property<int?>("ToDate")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("WorkWagesTapleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlmjalID")
                        .IsUnique()
                        .HasFilter("[AlmjalID] IS NOT NULL");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkWagesTapleID")
                        .IsUnique()
                        .HasFilter("[WorkWagesTapleID] IS NOT NULL");

                    b.ToTable("specificSpaceTemplates");
                });

            modelBuilder.Entity("Test.Models.TanjezOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessRoadType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AcountPiese")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdditionalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Alhiaza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allowance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AreaDifferent")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordinatesX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordinatesY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateOrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescripPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Directorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MaximumDuration")
                        .HasColumnType("datetime2");

                    b.Property<string>("OverNight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Space")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Transportation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TransportationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypePiece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.Property<decimal?>("WorkCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WorkOfferId")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("TanjezOrder");
                });

            modelBuilder.Entity("Test.Models.TransportModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AllowanceFees")
                        .HasColumnType("int");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsSelected")
                        .HasColumnType("int");

                    b.Property<int?>("OverNightFees")
                        .HasColumnType("int");

                    b.Property<string>("StatuseType1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatuseType2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransportationFees")
                        .HasColumnType("int");

                    b.Property<int?>("TransportationScheduleTemplateID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TransportationScheduleTemplateID");

                    b.HasIndex("UserID");

                    b.ToTable("TransportModels");
                });

            modelBuilder.Entity("Test.Models.TransportationScheduleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameTemplete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatuseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("TransportationScheduleTemplate");
                });

            modelBuilder.Entity("Test.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fourth_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frist_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Is_Authentic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number_card")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_number1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_number13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_number2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Second_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Third_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Test.Models.WorkContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdditionalCostsTotal")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdvancePaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AfterDeliveryPaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CamelResignationPenaltyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("EngineerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LatePenaltyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OnSitePaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ResignationAfterAdvancePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SecondParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Space")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Transportation")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkContractDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("WorkContractTime")
                        .HasColumnType("time");

                    b.Property<int?>("WorkCost")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkContract");
                });

            modelBuilder.Entity("Test.Models.WorkOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdditionalCostTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AdvancePaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AfterDeliveryPaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CamelResignationPenaltyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsAllTypesIncluded")
                        .HasColumnType("int");

                    b.Property<decimal?>("LatePenaltyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OnSitePaymentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ResignationAfterAdvancePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransportTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransportationScheduleTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WagesTemplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkWagesTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("WorkWagesType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalCostTypeId");

                    b.HasIndex("TransportationScheduleTemplateId");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkWagesTemplateId");

                    b.ToTable("WorkOffer");
                });

            modelBuilder.Entity("Test.Models.WorkWagesTaple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlmjalID")
                        .HasColumnType("int");

                    b.Property<string>("EachTypeSimilar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FromDate")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Price1")
                        .HasColumnType("int");

                    b.Property<string>("SpaceStandard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToDate")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkWagesTemplatesID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlmjalID")
                        .IsUnique()
                        .HasFilter("[AlmjalID] IS NOT NULL");

                    b.HasIndex("UserID");

                    b.HasIndex("WorkWagesTemplatesID");

                    b.ToTable("workWagesTaples");
                });

            modelBuilder.Entity("Test.Models.WorkWagesTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EachTypeSimilar")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WorkWagesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkWagesType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("WorkWagesTemplate");
                });

            modelBuilder.Entity("Test.Models.Workpaymentperiod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workpaymentperiods");
                });

            modelBuilder.Entity("Test.Models.ownership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ownerships");
                });

            modelBuilder.Entity("Test.Models.AdditionalCostModel", b =>
                {
                    b.HasOne("Test.Models.AdditionalCostType", "additionalCostType")
                        .WithMany("additionalCostModels")
                        .HasForeignKey("AdditionalCostTypeId");

                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("additionalCostModels")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");

                    b.Navigation("additionalCostType");
                });

            modelBuilder.Entity("Test.Models.AdditionalCostType", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("additionalCostTypes")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.AreaStandardFromTo", b =>
                {
                    b.HasOne("Test.Models.AreaStandardTemplate", null)
                        .WithMany("Standards")
                        .HasForeignKey("AreaStandardTemplateId");
                });

            modelBuilder.Entity("Test.Models.Certificate", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("certificates")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.Classification", b =>
                {
                    b.HasOne("Test.Models.Almjal", "Almjal")
                        .WithMany()
                        .HasForeignKey("AlmjalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almjal");
                });

            modelBuilder.Entity("Test.Models.ContractAmendment", b =>
                {
                    b.HasOne("Test.Models.WorkContract", "workContracts")
                        .WithMany("contractAmendments")
                        .HasForeignKey("WorkContractId");

                    b.Navigation("workContracts");
                });

            modelBuilder.Entity("Test.Models.ContractItem", b =>
                {
                    b.HasOne("Test.Models.WorkContract", "workContracts")
                        .WithMany("contractItems")
                        .HasForeignKey("WorkContractId");

                    b.Navigation("workContracts");
                });

            modelBuilder.Entity("Test.Models.EarthBorders", b =>
                {
                    b.HasOne("Test.Models.TanjezOrder", "tanjezOrder")
                        .WithMany("earthBorders")
                        .HasForeignKey("TanjezOrderID");

                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("earthBorders")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");

                    b.Navigation("tanjezOrder");
                });

            modelBuilder.Entity("Test.Models.Experience", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("experiences")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.Manager", b =>
                {
                    b.HasOne("Test.Models.Experience", "GetExperience")
                        .WithMany("ManagerList")
                        .HasForeignKey("ExperienceId");

                    b.Navigation("GetExperience");
                });

            modelBuilder.Entity("Test.Models.OfferTypeModel", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("offerTypeModels")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.Project", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("projects")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.Qualification", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("qualifications")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.SectionType", b =>
                {
                    b.HasOne("Test.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Test.Models.Skill", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("skills")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.SpecificSpaceTemplate", b =>
                {
                    b.HasOne("Test.Models.Almjal", "almjal")
                        .WithOne("specificSpaceTemplate")
                        .HasForeignKey("Test.Models.SpecificSpaceTemplate", "AlmjalID");

                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("specificSpaceTemplates")
                        .HasForeignKey("UserID");

                    b.HasOne("Test.Models.WorkWagesTaple", "workWagesTaple")
                        .WithOne("specificSpaceTemplate")
                        .HasForeignKey("Test.Models.SpecificSpaceTemplate", "WorkWagesTapleID");

                    b.Navigation("Users");

                    b.Navigation("almjal");

                    b.Navigation("workWagesTaple");
                });

            modelBuilder.Entity("Test.Models.TanjezOrder", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("tanjezOrders")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.TransportModel", b =>
                {
                    b.HasOne("Test.Models.TransportationScheduleTemplate", "transportationScheduleTemplate")
                        .WithMany("transportModels")
                        .HasForeignKey("TransportationScheduleTemplateID");

                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("transportModels")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");

                    b.Navigation("transportationScheduleTemplate");
                });

            modelBuilder.Entity("Test.Models.TransportationScheduleTemplate", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("transportationScheduleTemplates")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.WorkOffer", b =>
                {
                    b.HasOne("Test.Models.AdditionalCostType", "additionalCostType")
                        .WithMany("workOffers")
                        .HasForeignKey("AdditionalCostTypeId");

                    b.HasOne("Test.Models.TransportationScheduleTemplate", "transportationScheduleTemplate")
                        .WithMany("workOffers")
                        .HasForeignKey("TransportationScheduleTemplateId");

                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("workOffers")
                        .HasForeignKey("UserID");

                    b.HasOne("Test.Models.WorkWagesTemplate", "workWagesTemplate")
                        .WithMany("workOffers")
                        .HasForeignKey("WorkWagesTemplateId");

                    b.Navigation("Users");

                    b.Navigation("additionalCostType");

                    b.Navigation("transportationScheduleTemplate");

                    b.Navigation("workWagesTemplate");
                });

            modelBuilder.Entity("Test.Models.WorkWagesTaple", b =>
                {
                    b.HasOne("Test.Models.Almjal", "almjal")
                        .WithOne("workWagesTaple")
                        .HasForeignKey("Test.Models.WorkWagesTaple", "AlmjalID");

                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("workWagesTaples")
                        .HasForeignKey("UserID");

                    b.HasOne("Test.Models.WorkWagesTemplate", "WorkWagesTemplates")
                        .WithMany("workWagesTaples")
                        .HasForeignKey("WorkWagesTemplatesID");

                    b.Navigation("Users");

                    b.Navigation("WorkWagesTemplates");

                    b.Navigation("almjal");
                });

            modelBuilder.Entity("Test.Models.WorkWagesTemplate", b =>
                {
                    b.HasOne("Test.Models.User", "Users")
                        .WithMany("workWagesTemplates")
                        .HasForeignKey("UserID");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Test.Models.AdditionalCostType", b =>
                {
                    b.Navigation("additionalCostModels");

                    b.Navigation("workOffers");
                });

            modelBuilder.Entity("Test.Models.Almjal", b =>
                {
                    b.Navigation("specificSpaceTemplate");

                    b.Navigation("workWagesTaple");
                });

            modelBuilder.Entity("Test.Models.AreaStandardTemplate", b =>
                {
                    b.Navigation("Standards");
                });

            modelBuilder.Entity("Test.Models.Experience", b =>
                {
                    b.Navigation("ManagerList");
                });

            modelBuilder.Entity("Test.Models.TanjezOrder", b =>
                {
                    b.Navigation("earthBorders");
                });

            modelBuilder.Entity("Test.Models.TransportationScheduleTemplate", b =>
                {
                    b.Navigation("transportModels");

                    b.Navigation("workOffers");
                });

            modelBuilder.Entity("Test.Models.User", b =>
                {
                    b.Navigation("additionalCostModels");

                    b.Navigation("additionalCostTypes");

                    b.Navigation("certificates");

                    b.Navigation("earthBorders");

                    b.Navigation("experiences");

                    b.Navigation("offerTypeModels");

                    b.Navigation("projects");

                    b.Navigation("qualifications");

                    b.Navigation("skills");

                    b.Navigation("specificSpaceTemplates");

                    b.Navigation("tanjezOrders");

                    b.Navigation("transportModels");

                    b.Navigation("transportationScheduleTemplates");

                    b.Navigation("workOffers");

                    b.Navigation("workWagesTaples");

                    b.Navigation("workWagesTemplates");
                });

            modelBuilder.Entity("Test.Models.WorkContract", b =>
                {
                    b.Navigation("contractAmendments");

                    b.Navigation("contractItems");
                });

            modelBuilder.Entity("Test.Models.WorkWagesTaple", b =>
                {
                    b.Navigation("specificSpaceTemplate");
                });

            modelBuilder.Entity("Test.Models.WorkWagesTemplate", b =>
                {
                    b.Navigation("workOffers");

                    b.Navigation("workWagesTaples");
                });
#pragma warning restore 612, 618
        }
    }
}
