-- تحويل جميع أعمدة النصوص إلى NVARCHAR (UTF-8)
USE Awqaf33;
GO

-- Users table
ALTER TABLE Users ALTER COLUMN Frist_Name NVARCHAR(100) NOT NULL;
ALTER TABLE Users ALTER COLUMN Second_Name NVARCHAR(100) NOT NULL;
ALTER TABLE Users ALTER COLUMN Third_Name NVARCHAR(100) NOT NULL;
ALTER TABLE Users ALTER COLUMN Fourth_Name NVARCHAR(100) NOT NULL;
ALTER TABLE Users ALTER COLUMN Nickname NVARCHAR(50) NULL;
ALTER TABLE Users ALTER COLUMN User_type NVARCHAR(20) NULL;
ALTER TABLE Users ALTER COLUMN Img NVARCHAR(255) NULL;
ALTER TABLE Users ALTER COLUMN Cv NVARCHAR(255) NULL;
ALTER TABLE Users ALTER COLUMN Is_Authentic NVARCHAR(50) NULL;
ALTER TABLE Users ALTER COLUMN Phone_number1 NVARCHAR(20) NOT NULL;
ALTER TABLE Users ALTER COLUMN Phone_number2 NVARCHAR(20) NULL;
ALTER TABLE Users ALTER COLUMN Phone_number13 NVARCHAR(20) NULL;
ALTER TABLE Users ALTER COLUMN Email NVARCHAR(100) NULL;
ALTER TABLE Users ALTER COLUMN Pass NVARCHAR(100) NOT NULL;
ALTER TABLE Users ALTER COLUMN Sex NVARCHAR(10) NOT NULL;
ALTER TABLE Users ALTER COLUMN Nationality NVARCHAR(50) NOT NULL;
ALTER TABLE Users ALTER COLUMN MaritalStatus NVARCHAR(20) NOT NULL;
ALTER TABLE Users ALTER COLUMN RelativePhone NVARCHAR(20) NOT NULL;
GO

-- Almjals table  
ALTER TABLE Almjals ALTER COLUMN AlmjalName NVARCHAR(100) NOT NULL;
GO

-- Classification table
ALTER TABLE Classification ALTER COLUMN ClassificationName NVARCHAR(100) NOT NULL;
GO

-- WorkOffer table
ALTER TABLE WorkOffer ALTER COLUMN OfferName NVARCHAR(200) NULL;
ALTER TABLE WorkOffer ALTER COLUMN WagesTemplate NVARCHAR(100) NULL;
ALTER TABLE WorkOffer ALTER COLUMN TransportTemplate NVARCHAR(100) NULL;
ALTER TABLE WorkOffer ALTER COLUMN WorkWagesType NVARCHAR(50) NULL;
ALTER TABLE WorkOffer ALTER COLUMN Notes NVARCHAR(500) NULL;
GO

-- Projects table
ALTER TABLE Projects ALTER COLUMN ProjName NVARCHAR(200) NULL;
ALTER TABLE Projects ALTER COLUMN ProjCompany NVARCHAR(200) NULL;
ALTER TABLE Projects ALTER COLUMN ProjField NVARCHAR(100) NULL;
ALTER TABLE Projects ALTER COLUMN ProjFrom NVARCHAR(20) NULL;
ALTER TABLE Projects ALTER COLUMN ProjTo NVARCHAR(20) NULL;
ALTER TABLE Projects ALTER COLUMN ProjValue NVARCHAR(50) NULL;
ALTER TABLE Projects ALTER COLUMN ProjRole NVARCHAR(100) NULL;
GO

-- Certificates table
ALTER TABLE Certificates ALTER COLUMN Type NVARCHAR(50) NULL;
ALTER TABLE Certificates ALTER COLUMN Almgal NVARCHAR(MAX) NULL;
ALTER TABLE Certificates ALTER COLUMN Depart NVARCHAR(100) NULL;
ALTER TABLE Certificates ALTER COLUMN CertName NVARCHAR(MAX) NULL;
ALTER TABLE Certificates ALTER COLUMN CertOrg NVARCHAR(200) NULL;
ALTER TABLE Certificates ALTER COLUMN CertYear NVARCHAR(MAX) NULL;
ALTER TABLE Certificates ALTER COLUMN CertType NVARCHAR(MAX) NOT NULL;
GO

-- Notifications table
ALTER TABLE Notifications ALTER COLUMN UserType NVARCHAR(20) NULL;
ALTER TABLE Notifications ALTER COLUMN Message NVARCHAR(MAX) NOT NULL;
ALTER TABLE Notifications ALTER COLUMN Url NVARCHAR(500) NULL;
GO

-- Lands table
ALTER TABLE Lands ALTER COLUMN ParcelNumber NVARCHAR(50) NOT NULL;
ALTER TABLE Lands ALTER COLUMN OwnerName NVARCHAR(100) NOT NULL;
ALTER TABLE Lands ALTER COLUMN Shape NVARCHAR(MAX) NOT NULL;
ALTER TABLE Lands ALTER COLUMN CreatedBy NVARCHAR(100) NOT NULL;
ALTER TABLE Lands ALTER COLUMN UpdatedBy NVARCHAR(100) NOT NULL;
GO

PRINT 'تم تحويل جميع الجداول إلى UTF-8 (NVARCHAR) بنجاح!';
