name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Verify
        run: |
          echo "Mahwar project connected successfully"
          echo "GitHub Actions is working"